### ISSUE TITLE
Could not find artifact com.oracle.coherence:coherence:jar:12.1.2-0-0 in central

### ISSUE THREAD

**Issue by lurodrig** [coherence-community/coherence-hibernate#16]
Hello there,

I am trying to use the `coherence-hibernate-second-level-cache` in my project:
```
        <dependency>
            <groupId>com.oracle.coherence.hibernate</groupId>
            <artifactId>coherence-hibernate-second-level-cache</artifactId>
            <version>1.0.0</version>
        </dependency>
```

However when I try to package it I get: `Could not find artifact com.oracle.coherence:coherence:jar:12.1.2-0-0 in central (https://repo.maven.apache.org/maven2)`

I've been looking for that version but I did not find it anywhere (oracle downloads, maven central, mvnrepository.com...). In Oracle downloads I found the installer [1], but if I have to install, extract the coherence jar and add it manually to my repo, uf...

Any thoughts on this?

Thanks in advance,

Luis

[1] http://download.oracle.com/otn/nt/middleware/12c/12212/fmw_12.2.1.2.0_coherence_Disk1_1of1.zip

**Comment by ghillert** [comment]
Hi Luis - Thanks for your interest! We are in the process of updating the repo, literally as I am writing this - Please stand-by for another day or so and everything will be reasonably up-to-date. By the default, the updated repo will build against the latest OSS Coherence CE version ... https://coherence.community/ and initially provide support for Hibernate `4.3.x`, `5` to `5.2.x`. With support for `5.3.x` to `5.4.x` added in the coming weeks.

**Comment by ghillert** [comment]
See https://github.com/coherence-community/coherence-hibernate/pull/14

**Comment by lurodrig** [comment]
Hello @ghillert 

Wow these are really good news, thank you very much for your prompt response!

Our idea would be to use `coherence-hibernate-second-level-cache` on the application side (hibernate 4.3.10 + spring 4.1.8) against coherence cluster in k8s deployed with the [coherence-operator](https://oracle.github.io/coherence-operator/)

Thanks again!

Cheers,

Luis

**Comment by ghillert** [comment]
I have been quite on the fence about Hibernate `4.3.x` ... It is now 7 years old. Do you have any plans to update?

**Comment by lurodrig** [comment]
Hello @ghillert,

Yes, I know, I know... I would like to answer you with a big YES, but unfortunately I am not part of the development team of that application, I am just the middleware guy :)

Trouble is that we still have to maintain a number of legacy applications that run old versions of hibernate, spring and  other frameworks :grimacing:

In the case of this specific one we were using memcache and nowadays hazlecast. The key point is that we are moving the applications to k8s, that's why coherence CE + operator looks like it can match perfectly our infrastructure.

Thanks and best regards,

Luis

**Comment by ghillert** [comment]
Aloha Luis - While we don't have a release, yet, the SNAPSHOT builds are now published to Maven Central. I have also created a simple demo using Spring Boot at https://github.com/ghillert/coherence-hibernate-demo. I hope this helps until we publish milestone releases.

**Comment by lurodrig** [comment]
Hey @ghillert,

Thank you very much! It works like a charm! :+1: 

Good, now my next step is to make it work together with the coherence docker image [1]
```
+---------------------------+                         +----------------------------------------+
|                           |                         |                                        |
| coherence-hibernate-demo  +------------------------>+ oracle/coherence:12.2.1.3.0-standalone |
|                           |                         |                                        |
+---------------------------+                         +----------------------------------------+
```

Cheers,

Luis








[1] https://github.com/oracle/docker-images/tree/master/OracleCoherence/docs/00.imageusage

**Comment by lurodrig** [comment]
Hi again @ghillert,

Trying
```
        <dependency>
            <groupId>com.oracle.coherence.hibernate</groupId>
            <artifactId>coherence-hibernate-second-level-cache</artifactId>
            <version>2.0.0-SNAPSHOT</version>
        </dependency>
```
I am getting
```
Could not find artifact com.oracle.coherence.hibernate:coherence-hibernate-second-level-cache:jar:2.0.0-SNAPSHOT in central (https://repo1.maven.org/maven2)
```
Maybe it needs a bit of time.

Thanks in advance,

Luis

ps: just in case I enabled snapshots ;)
```
<repositories>
  <repository>
    <id>central</id>
    <name>Maven Repository Switchboard</name>
    <layout>default</layout>
    <url>https://repo1.maven.org/maven2</url>
    <snapshots>
      <enabled>true</enabled>
    </snapshots>
  </repository>
</repositories>
```

**Comment by ghillert** [comment]
Sorry for the delay - you need to use the SNAPHOTS repository: https://oss.sonatype.org/content/repositories/snapshots. If you  checkout the [demo](https://github.com/ghillert/coherence-hibernate-demo), it should build without any issues. I hope this gets you past the hurdle.
